
services:
  php:
    image: nastyaklyueva/user-auth-php:latest
    container_name: my_php
    volumes:
      - ../symfony_user_auth:/var/www/html
    working_dir: /var/www/html
    environment:
      APP_ENV: dev
    depends_on:
      - database
      - redis

  nginx:
    image: nginx:stable
    container_name: my_nginx
    ports:
      - "8080:80"
    volumes:
      - ../symfony_user_auth:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
